# Generated by Django 6.0.3 on 2026-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100, unique=True, verbose_name='المحافظة')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الشحن')),
                ('enabled', models.BooleanField(default=True, verbose_name='متاح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'منطقة شحن',
                'verbose_name_plural': 'مناطق الشحن',
                'ordering': ['order', 'governorate'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
