# Generated by Django 5.0.12 on 2026-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productvariant_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('deposit', 'الدفع عند الاستلام'), ('vodafone', 'Vodafone Cash'), ('instapay', 'InstaPay'), ('bank', 'تحويل بنكي'), ('card', 'بطاقة بنكية'), ('paybump', 'PayBump — دفع مباشر')], default='deposit', max_length=20),
        ),
    ]
