# Generated by Django 5.0.12 on 2026-04-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
